const ships = [
  {
    index: 0,
    shipName: "Aircraft-Carrier",
    letter: "A",
    hits: 0,
    totalHealth: 5,
    isSunk: false,
    isPlaced: false,
    source: "./assets/Aircraft-Carrier.png",
  },
  {
    index: 1,
    shipName: "Battleship",
    letter: "B",
    hits: 0,
    totalHealth: 4,
    isSunk: false,
    isPlaced: false,
    source: "./assets/Battleship.png",
  },
  {
    index: 2,
    shipName: "Destroyer",
    letter: "D",
    hits: 0,
    totalHealth: 3,
    isSunk: false,
    isPlaced: false,
    source: "./assets/Destroyer.png",
  },
  {
    index: 3,
    shipName: "Submarine",
    letter: "S",
    hits: 0,
    totalHealth: 3,
    isSunk: false,
    isPlaced: false,
    source: "./assets/Submarine.png",
  },
  {
    index: 4,
    shipName: "Boat",
    letter: "T",
    hits: 0,
    totalHealth: 2,
    isSunk: false,
    isPlaced: false,
    source: "./assets/Boat.png",
  },
];

export default ships;
